# MAPPO Configuration

cnn_input: &cnn_input 4
num_episode: &num_ep 80

# Environment Settings
env:
  stack_size: *cnn_input     # Stack Size
  frame_size: [64, 64]       # Frame Size
  max_cycles: *num_ep            # Num of episodes

seed: 42


# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/latest/api/utils/model_instantiators.html
models:
  separate: True
  local_cnn:
    input_channel: *cnn_input
    layers: [32, 64, 128]
    output: 512
  global_cnn:
    input_channel: 1
    layers: [32, 64, 128]
    output: 512
  policy:  # see gaussian_model parameters
    clip_actions: False
    clip_log_std: True
    min_log_std: -20.0
    max_log_std: 2.0
  value:  # see deterministic_model parameters
    clip_actions: False


# Rollout memory
# https://skrl.readthedocs.io/en/latest/api/memories/random.html
memory:
  class: RandomMemory
  memory_size: -1  # automatically determined (same as agent:rollouts)


# MAPPO agent configuration (field names are from MAPPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/multi_agents/mappo.html
agent:
  class: MAPPO
  rollouts: *num_ep
  learning_epochs: 8
  mini_batches: 1
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 3.0e-04
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.01
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs:
    dim: *cnn_input
  shared_state_preprocessor: RunningStandardScaler
  shared_state_preprocessor_kwargs:
    dim: 1
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.01
  value_loss_scale: 1.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: False
  # logging and checkpoint
  experiment:
    directory: "piston_push"
    experiment_name: ""
    write_interval: auto
    # 100 * rollouts
    checkpoint_interval: 8000


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  class: SequentialTrainer
  # rollouts*1000 iterations
  timesteps: 125000
  environment_info: log

log:
  use_wandb: False